WeaponDefinitionCatalog = WeaponDefinitionCatalog or {}

-- Each attachment defines: id, itemName, label, slot,
-- nativeComponentName, conflicts, prerequisites, removable, and optional tags.
WeaponDefinitionCatalog.attachments = {
    cattleman_long_barrel = {
        id = "cattleman_long_barrel",
        kind = "attachment",
        itemName = "cattleman_long_barrel",
        label = "Cattleman Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_REVOLVER_CATTLEMAN_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "cattleman" }
    },
    cattleman_wide_sight = {
        id = "cattleman_wide_sight",
        kind = "attachment",
        itemName = "cattleman_wide_sight",
        label = "Cattleman Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_REVOLVER_CATTLEMAN_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "cattleman" }
    },
    schofield_short_barrel = {
        id = "schofield_short_barrel",
        kind = "attachment",
        itemName = "schofield_short_barrel",
        label = "Schofield Short Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_REVOLVER_SCHOFIELD_BARREL_SHORT",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "schofield" }
    },
    schofield_wide_sight = {
        id = "schofield_wide_sight",
        kind = "attachment",
        itemName = "schofield_wide_sight",
        label = "Schofield Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_REVOLVER_SCHOFIELD_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "schofield" }
    },
    lemat_long_barrel = {
        id = "lemat_long_barrel",
        kind = "attachment",
        itemName = "lemat_long_barrel",
        label = "LeMat Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_REVOLVER_LEMAT_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "lemat" }
    },
    lemat_wide_sight = {
        id = "lemat_wide_sight",
        kind = "attachment",
        itemName = "lemat_wide_sight",
        label = "LeMat Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_REVOLVER_LEMAT_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "lemat" }
    },
    navy_long_barrel = {
        id = "navy_long_barrel",
        kind = "attachment",
        itemName = "navy_long_barrel",
        label = "Navy Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_REVOLVER_NAVY_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "navy" }
    },
    navy_wide_sight = {
        id = "navy_wide_sight",
        kind = "attachment",
        itemName = "navy_wide_sight",
        label = "Navy Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_REVOLVER_NAVY_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "navy" }
    },
    doubleaction_long_barrel = {
        id = "doubleaction_long_barrel",
        kind = "attachment",
        itemName = "doubleaction_long_barrel",
        label = "Double-Action Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_REVOLVER_DOUBLEACTION_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "doubleaction" }
    },
    doubleaction_wide_sight = {
        id = "doubleaction_wide_sight",
        kind = "attachment",
        itemName = "doubleaction_wide_sight",
        label = "Double-Action Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_REVOLVER_DOUBLEACTION_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "doubleaction" }
    },
    m1899_long_barrel = {
        id = "m1899_long_barrel",
        kind = "attachment",
        itemName = "m1899_long_barrel",
        label = "M1899 Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_PISTOL_M1899_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "m1899" }
    },
    m1899_wide_sight = {
        id = "m1899_wide_sight",
        kind = "attachment",
        itemName = "m1899_wide_sight",
        label = "M1899 Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_PISTOL_M1899_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "m1899" }
    },
    volcanic_long_barrel = {
        id = "volcanic_long_barrel",
        kind = "attachment",
        itemName = "volcanic_long_barrel",
        label = "Volcanic Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_PISTOL_VOLCANIC_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "volcanic" }
    },
    volcanic_wide_sight = {
        id = "volcanic_wide_sight",
        kind = "attachment",
        itemName = "volcanic_wide_sight",
        label = "Volcanic Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_PISTOL_VOLCANIC_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "volcanic" }
    },
    semiauto_long_barrel = {
        id = "semiauto_long_barrel",
        kind = "attachment",
        itemName = "semiauto_long_barrel",
        label = "Semi-Automatic Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_PISTOL_SEMIAUTO_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "semiauto" }
    },
    semiauto_wide_sight = {
        id = "semiauto_wide_sight",
        kind = "attachment",
        itemName = "semiauto_wide_sight",
        label = "Semi-Automatic Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_PISTOL_SEMIAUTO_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "semiauto" }
    },
    mauser_long_barrel = {
        id = "mauser_long_barrel",
        kind = "attachment",
        itemName = "mauser_long_barrel",
        label = "Mauser Long Barrel",
        slot = "barrel",
        nativeComponentName = "COMPONENT_PISTOL_MAUSER_BARREL_LONG",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "mauser" }
    },
    mauser_wide_sight = {
        id = "mauser_wide_sight",
        kind = "attachment",
        itemName = "mauser_wide_sight",
        label = "Mauser Wide Sight",
        slot = "sight",
        nativeComponentName = "COMPONENT_PISTOL_MAUSER_SIGHT_WIDE",
        conflicts = {},
        prerequisites = {},
        removable = true,
        tags = { "functional", "mauser" }
    }
}
