import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const manifest = read('fxmanifest.lua');
assert(manifest.indexOf('/shared/ammunition_pools.lua') < manifest.indexOf('/client/firearm_pools.lua'));
assert(manifest.indexOf('/client/firearm_pools.lua') < manifest.indexOf('/client/main.lua'));
const source = read('client/main.lua');
assert.match(source, /if FirearmPoolModuleReady\(\) then FeatherFirearmPools.Reset\(\) end/);
assert.match(source, /slots\[slot\]\.ammoPools and not FirearmPoolModuleReady\(\)/);
assert.match(source, /code = 'firearm_pool_module_missing'/);
assert.match(source, /if characterRestoreInFlight or not characterRestoreComplete then/);
assert.match(source, /and characterRestoreComplete and not characterRestoreInFlight/);
const holster = source.slice(source.indexOf('local function ScheduleRestoredWeaponsHolster()'), source.indexOf('function FeatherWeaponsClient.Reconcile'));
assert.match(holster, /FeatherFirearmPools\.Restore\(ped, allSlots, WeaponDefinitionCatalog\)/);
assert.match(source, /if state\.ammoPools then return end/);
assert.match(source, /if not sharedAmmo and not \(primary\.ammoPools and secondary\.ammoPools\) then/);
assert.match(source, /code == 'rate_limited' and 15000 or 2000/);
assert.match(source, /message=%s detail=%s/);
console.log('Optional pool module startup ordering and fail-closed guards passed.');
